apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-voting-app
specs:
  containers:
    - name: worker-app
    image: kodekloud/examplevotingapp_worker:v1
